services:
  client:
    build:
      context: ./client
    ports:
      - "5173:80"
    depends_on:
      - server
   
  server:
    build:
      context: ./server
    ports:
      - "3002:3002"
    env_file:
      - ./server/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      mongo:
        condition: service_started
   
  db:
    image: mysql:8.0
    command: --sql-mode=""
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: task_manager
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ppass"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 30s
   
  redis:
    image: redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
   
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  mysql_data: