services:
  client:
    build:
      context: ./client
    ports:
      - "5173:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "3002:3002"
    env_file:
      - ./server/.env
    depends_on:
      - db
      - redis
      - mongo

  db:
    image: mysql:8.0
    command: --sql-mode=""
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: task_manager
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis
    ports:
      - "6380:6379"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

volumes:
  mysql_data:
